global:
  scrape_interval: 2s

scrape_configs:
  - job_name: castlekv
    static_configs:
      - targets:
          - localhost:8080
          - host.docker.internal:8080
          - 172.22.227.69:8080

  - job_name: pushgateway
    static_configs:
      - targets:
          - pushgateway:9091