# Two-Node Server Configuration
# This file contains configurations for a two-node server deployment.

# =====================================
# Node 1 Configuration
# =====================================

# Node Identity Configuration
partition_id: 0
replica_id: 0

# Network Configuration
client_listen_addr: "0.0.0.0:23000"
peer_listen_addr: "0.0.0.0:25000"
manager_addr: "0.0.0.0:24000"

# Peer replica addresses - maps replica IDs to their addresses
# In this case, node 1 connects to node 2
peer_replica_addr:
  1: "0.0.0.0:25001"  # Address of node 2 (modify with actual IP)

# Storage Configuration
persistence_enabled: true
db_path: "data/db1"
log_path: "data/log1"
persistent_state_path: "data/state1"
log_seg_entry_size: 1048576  # 1MB

# Performance Tuning
batch_size: 100
batch_timeout_ms: 1000